apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: api
          ports:
            - containerPort: 80
